IMAGE = "ubuntu/bionic64"
# if you want to increase the number of worker nodes
# you need to add them to the inventory file
WORKERS = 2

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      if [ ! -f ~/.initial_config_done ]; then
        cat /vagrant/ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
        cat /vagrant/ssh/id_rsa.pub > /home/vagrant/.ssh/id_rsa.pub
        cat /vagrant/ssh/id_rsa > /home/vagrant/.ssh/id_rsa
        chown -R vagrant:vagrant /home/vagrant/.ssh
        chmod 600 /home/vagrant/.ssh/*
        touch ~/.initial_config_done
      fi
    SHELL
  end

  (1..WORKERS).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = IMAGE
      worker.disksize.size = '50GB'
      worker.vm.network :private_network, ip: "192.168.10.#{i + 10}"
      worker.vm.hostname = "worker#{i}.roz"
    end
  end

  config.vm.define "master" do |master|
    master.vm.box = IMAGE
    master.disksize.size = '50GB'
    master.vm.network :private_network, ip: "192.168.10.10"
    master.vm.hostname = "master.roz"

    master.vm.provision "master", type: "ansible_local" do |ansible|
      ansible.verbose = true
      ansible.install = true
      ansible.install_mode = "default"
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/master.yaml"
      ansible.inventory_path = "ansible/inventory"
      ansible.limit = "master"
      ansible.extra_vars = {
          node_ip: "192.168.10.10",
      }
    end

    (1..WORKERS).each do |i|
      master.vm.provision "worker#{i}", type: "ansible_local" do |ansible|
        ansible.verbose = true
        ansible.config_file = "ansible/ansible.cfg"
        ansible.playbook = "ansible/workers.yaml"
        ansible.inventory_path = "ansible/inventory"
        ansible.limit = "worker#{i}"
        ansible.extra_vars = {
            node_ip: "192.168.10.#{i+10}",
        }
      end
    end

    master.vm.provision "all", type: "ansible_local" do |ansible|
      ansible.verbose = true
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/config-on-all.yaml"
      ansible.inventory_path = "ansible/inventory"
      ansible.limit = "all"
    end

    master.vm.provision "masterconf", type: "ansible_local" do |ansible|
      ansible.verbose = true
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/config-on-master.yaml"
      ansible.inventory_path = "ansible/inventory"
      ansible.limit = "master"
    end

  end
end
