apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: jenkins-pv
  resources:
    requests:
      storage: 10Gi
