apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: jenkins
spec:
  storageClassName: nexus-pv
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: /nexusVol
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
